[toolchain]
anchor_version = "0.32.1"
solana_version = "2.2.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
sable = "SaSAXcdWhyr1KD8TKRg6K7WPuxcPLZJHKEwsjQgL5Di"

[programs.devnet]
sable = "SaSAXcdWhyr1KD8TKRg6K7WPuxcPLZJHKEwsjQgL5Di"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
